name: Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          token: ${{ secrets.GH_TOKEN }}
      - uses: actions/setup-node@v3.6.0
        with:
          node-version-file: '.tool-versions'
      - run: yarn install
      - run: yarn run build
      - run: yarn run export
      - uses: peaceiris/actions-gh-pages@v3.9.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
