name: Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3.6.0
      - run: yarn install
      - run: yarn run prepare:filename
      - run: yarn run prepare:data
      - run: yarn run build:app
      - run: yarn run export
      - uses: peaceiris/actions-gh-pages@v3.9.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
